controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

login:
    path: /api/login
    methods: ['POST']
    controller: App\Controller\LoginController

auth:
    path: /api/auth
    methods: ['POST']
    controller: App\Controller\AuthJWTController