name: My docker

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test the Docker image
        uses: docker/test-action@v2
        with:
            context: .
            tags: "test"


  build:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Test the Docker image
        uses: docker/test-action@v2
        with:
            context: .
            tags: "${{ env.DOCKER_TAG }}"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenge:test-deploy
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}