name: My docker

on:
  push:
    branches:
      - master

env:
  DOCKER_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Dockerfile
          push: true
          tags: test-deploy
        env:
          DOCKER_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}